logLevel: info

api: yes
apiAddress: :9997

authMethod: internal
authInternalUsers:
  - user: any
    permissions:
      - action: read
      - action: playback
  - user: ${MEDIAMTX_API_USER}
    pass: ${MEDIAMTX_API_PASS}
    permissions:
      - action: publish
      - action: read
      - action: playback
      - action: api
      - action: metrics

metrics: yes
metricsAddress: :9998

rtsp: yes
rtspAddress: :8554
rtspTransports: [tcp, udp]

hls: yes
hlsAddress: :8888
hlsAllowOrigins: ['${MEDIAMTX_HLS_ALLOW_ORIGIN}']
hlsAlwaysRemux: false
hlsVariant: lowLatency
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
hlsSegmentCount: 7

webrtc: yes
webrtcAddress: :8889
webrtcAllowOrigins: ['${MEDIAMTX_WEBRTC_ALLOW_ORIGIN}']
webrtcLocalUDPAddress: :8189
webrtcAdditionalHosts: ['${MEDIAMTX_WEBRTC_ADDITIONAL_HOST}']

pathDefaults:
  rtspTransport: tcp

paths:
  all_others:
