logLevel: info

api: yes
apiAddress: :9997

authMethod: internal
authInternalUsers:
  - user: any
    permissions:
      - action: publish
      - action: read
      - action: playback
  - user: ${MEDIAMTX_API_USER}
    pass: ${MEDIAMTX_API_PASS}
    permissions:
      - action: api
      - action: metrics

metrics: yes
metricsAddress: :9998

rtsp: yes
rtspAddress: :8554
rtspTransports: [tcp, udp]

hls: yes
hlsAddress: :8888
hlsAllowOrigins: ['*']
hlsAlwaysRemux: true
hlsVariant: fmp4

webrtc: yes
webrtcAddress: :8889
webrtcAllowOrigins: ['*']

pathDefaults:
  rtspTransport: tcp

paths:
  all_others:
