ALTER TABLE "Camera"
  ADD COLUMN "recordingMode" TEXT NOT NULL DEFAULT 'continuous',
  ADD COLUMN "retentionDays" INTEGER NOT NULL DEFAULT 7,
  ADD COLUMN "preferredRtspTransport" TEXT NOT NULL DEFAULT 'tcp',
  ADD COLUMN "preferredLiveProtocol" TEXT NOT NULL DEFAULT 'flv',
  ADD COLUMN "streamVideoCodec" TEXT,
  ADD COLUMN "streamWidth" INTEGER,
  ADD COLUMN "streamHeight" INTEGER,
  ADD COLUMN "streamFps" INTEGER,
  ADD COLUMN "streamBitrateKbps" INTEGER,
  ADD COLUMN "recordingVideoCodec" TEXT,
  ADD COLUMN "recordingWidth" INTEGER,
  ADD COLUMN "recordingHeight" INTEGER,
  ADD COLUMN "recordingFps" INTEGER,
  ADD COLUMN "recordingBitrateKbps" INTEGER,
  ADD COLUMN "audioEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "detectedVideoCodec" TEXT,
  ADD COLUMN "detectedWidth" INTEGER,
  ADD COLUMN "detectedHeight" INTEGER,
  ADD COLUMN "detectedFps" INTEGER,
  ADD COLUMN "detectedBitrateKbps" INTEGER;
