export const envConfig = () => ({
  apiPort: Number(process.env.API_PORT ?? 3000),
  corsAllowedOrigins: process.env.CORS_ALLOWED_ORIGINS ?? 'http://localhost:5173',
  databaseUrl: process.env.DATABASE_URL ?? '',
  redisHost: process.env.REDIS_HOST ?? 'localhost',
  redisPort: Number(process.env.REDIS_PORT ?? 6379),
  cameraSecretKey: process.env.CAMERA_SECRET_KEY ?? '',
  ffmpegRtspTransport: process.env.FFMPEG_RTSP_TRANSPORT ?? 'tcp',
  ffmpegRtspFallbackTransports: process.env.FFMPEG_RTSP_FALLBACK_TRANSPORTS ?? 'tcp,udp',
  ffmpegRtspFallbackPorts: process.env.FFMPEG_RTSP_FALLBACK_PORTS ?? '51488,51489,51490',
  ffmpegRtspEnablePortFallback: String(process.env.FFMPEG_RTSP_ENABLE_PORT_FALLBACK ?? 'false') === 'true',
  ffmpegStimeoutUs: Number(process.env.FFMPEG_STIMEOUT_US ?? 8000000),
  ffmpegMaxDelayUs: Number(process.env.FFMPEG_MAX_DELAY_US ?? 500000),
  ffmpegProbesize: Number(process.env.FFMPEG_PROBESIZE ?? 32768),
  ffmpegAnalyzedurationUs: Number(process.env.FFMPEG_ANALYZEDURATION_US ?? 1000000),
  mjpegFps: Number(process.env.MJPEG_FPS ?? 20),
  mjpegQ: Number(process.env.MJPEG_Q ?? 5),
  recordingsRoot: process.env.RECORDINGS_ROOT ?? './storage/recordings',
  storageBackend: process.env.STORAGE_BACKEND ?? 'local',
  storageWriteProbeEnabled: String(process.env.STORAGE_WRITE_PROBE_ENABLED ?? 'true') !== 'false',
  recordingSegmentSeconds: Number(process.env.RECORDING_SEGMENT_SECONDS ?? 300),
  recordingMinFreeBytes: Number(process.env.RECORDING_MIN_FREE_BYTES ?? 2147483648),
  recordingMinFreePercent: Number(process.env.RECORDING_MIN_FREE_PERCENT ?? 5),
  ffmpegRecordingFormat: process.env.FFMPEG_RECORDING_FORMAT ?? 'mp4',
  ffmpegRecordingCopyCodec: process.env.FFMPEG_RECORDING_COPY_CODEC ?? 'true',
  recordingControlMode: process.env.RECORDING_CONTROL_MODE ?? 'local',
  workerCommandChannel: process.env.WORKER_COMMAND_CHANNEL ?? 'camera:commands',
  recordingThumbnailSecond: Number(process.env.RECORDING_THUMBNAIL_SECOND ?? 2),
  streamIncidentCooldownSeconds: Number(process.env.STREAM_INCIDENT_COOLDOWN_SECONDS ?? 120),
  healthAutoRemediationEnabled: String(process.env.HEALTH_AUTO_REMEDIATION_ENABLED ?? 'true') !== 'false',
  healthAutoRemediationMaxPerRun: Number(process.env.HEALTH_AUTO_REMEDIATION_MAX_PER_RUN ?? 5),
  alertScoreWarning: Number(process.env.ALERT_SCORE_WARNING ?? 75),
  alertScoreCritical: Number(process.env.ALERT_SCORE_CRITICAL ?? 60),
  alertOpenIncidentsCritical: Number(process.env.ALERT_OPEN_INCIDENTS_CRITICAL ?? 5),
  alertRecentWindowMinutes: Number(process.env.ALERT_RECENT_WINDOW_MINUTES ?? 60),
  jwtSecret: process.env.JWT_SECRET ?? '',
  jwtExpiresIn: process.env.JWT_EXPIRES_IN ?? '8h',
  evidenceHmacSecret: process.env.EVIDENCE_HMAC_SECRET ?? '',
  evidenceHmacKeyId: process.env.EVIDENCE_HMAC_KEY_ID ?? 'local-v1',
  alarmWebhookDefaultUrl: process.env.ALARM_WEBHOOK_DEFAULT_URL ?? '',
  alarmWebhookAllowedHosts: process.env.ALARM_WEBHOOK_ALLOWED_HOSTS ?? '',
  alarmWebhookSigningSecret: process.env.ALARM_WEBHOOK_SIGNING_SECRET ?? '',
  alarmEmailFrom: process.env.ALARM_EMAIL_FROM ?? '',
  smtpHost: process.env.SMTP_HOST ?? '',
  smtpPort: Number(process.env.SMTP_PORT ?? 587),
  smtpSecure: String(process.env.SMTP_SECURE ?? 'false') === 'true',
  smtpUser: process.env.SMTP_USER ?? '',
  smtpPass: process.env.SMTP_PASS ?? '',
  streamTokenExpiresIn: process.env.STREAM_TOKEN_EXPIRES_IN ?? '5m',
  mediaMtxEnabled: String(process.env.MEDIAMTX_ENABLED ?? 'true') !== 'false',
  mediaMtxApiBaseUrl: process.env.MEDIAMTX_API_BASE_URL ?? 'http://mediamtx:9997',
  mediaMtxApiUser: process.env.MEDIAMTX_API_USER ?? '',
  mediaMtxApiPass: process.env.MEDIAMTX_API_PASS ?? '',
  mediaMtxPublicHost: process.env.MEDIAMTX_PUBLIC_HOST ?? '',
  mediaMtxPublicScheme: process.env.MEDIAMTX_PUBLIC_SCHEME ?? '',
  mediaMtxHlsPort: Number(process.env.MEDIAMTX_HLS_PORT ?? 8888),
  mediaMtxWebrtcPort: Number(process.env.MEDIAMTX_WEBRTC_PORT ?? 8889),
  adminEmail: process.env.ADMIN_EMAIL ?? 'admin@local.dev',
  adminPassword: process.env.ADMIN_PASSWORD ?? '',
  adminName: process.env.ADMIN_NAME ?? 'Administrador',
  internalServiceToken: process.env.INTERNAL_SERVICE_TOKEN ?? '',
  cameraTestAllowPublicIp: String(process.env.CAMERA_TEST_ALLOW_PUBLIC_IP ?? 'false') === 'true',
  retentionDays: Number(process.env.RETENTION_DAYS ?? 7),
  retentionUseBullmq: String(process.env.RETENTION_USE_BULLMQ ?? 'true') !== 'false',
  healthCheckOfflineMinutes: Number(process.env.HEALTHCHECK_OFFLINE_MINUTES ?? 5),
});
