import { StyleSheet } from 'react-native';
import { BOTTOM_SAFE, TOP_SAFE } from '../config';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#020617' },
  content: { padding: 16, paddingTop: TOP_SAFE + 24, paddingBottom: BOTTOM_SAFE + 118, backgroundColor: '#020617' },
  page: { gap: 18 },
  dashboardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  dashboardTitle: { color: '#ffffff', fontSize: 28, fontWeight: '900', letterSpacing: -0.6 },
  dashboardSubtitle: { color: '#94a3b8', fontSize: 14, marginTop: 4, fontWeight: '600' },
  previewLimitHint: { color: '#64748b', fontSize: 11, lineHeight: 16, marginTop: 6, fontWeight: '700' },


  groupBlock: { gap: 13, marginTop: 4 },
  groupHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 3 },
  groupTitle: { color: '#f8fafc', fontSize: 14, fontWeight: '900' },
  groupCount: { color: '#64748b', fontSize: 12, fontWeight: '800' },
  cameraCard: { height: 218, borderRadius: 28, overflow: 'hidden', backgroundColor: '#0f172a', borderWidth: 1, borderColor: 'rgba(30,41,59,0.86)', shadowColor: '#000', shadowOpacity: 0.38, shadowRadius: 18, elevation: 6 },
  cameraPreview: { position: 'absolute', left: 0, right: 0, top: 0, height: 160, backgroundColor: '#1e293b', overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  cameraPreviewImage: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover', opacity: 0.9 },
  cameraPreviewFallback: { position: 'absolute', width: '100%', height: '100%', backgroundColor: '#111827', alignItems: 'center', justifyContent: 'center' },
  cameraPreviewShade: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(2,6,23,0.12)' },
  cameraPreviewText: { color: '#34d399', fontSize: 12, fontWeight: '900', letterSpacing: 2.2 },
  liveBadge: { position: 'absolute', left: 18, top: 18, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 7, flexDirection: 'row', gap: 7, alignItems: 'center', borderWidth: 1 },
  liveBadgeOnline: { backgroundColor: 'rgba(15,23,42,0.55)', borderColor: 'rgba(255,255,255,0.12)' },
  liveBadgeOffline: { backgroundColor: 'rgba(244,63,94,0.18)', borderColor: 'rgba(244,63,94,0.36)' },
  liveDot: { width: 7, height: 7, borderRadius: 4 },
  liveDotOnline: { backgroundColor: '#34d399' },
  liveDotOffline: { backgroundColor: '#fb7185' },
  liveBadgeText: { fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  liveBadgeTextOnline: { color: '#a7f3d0' },
  liveBadgeTextOffline: { color: '#fecdd3' },
  cameraCardBody: { position: 'absolute', left: 0, right: 0, bottom: 0, minHeight: 58, zIndex: 5, gap: 2, backgroundColor: '#0f172a', borderTopWidth: 1, borderColor: 'rgba(30,41,59,0.72)', paddingHorizontal: 18, paddingVertical: 9 },
  cameraCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  cameraName: { color: '#ffffff', fontWeight: '900', fontSize: 16, flexShrink: 1, letterSpacing: 0.1 },
  cameraMeta: { color: '#94a3b8', fontSize: 12, marginTop: 2, fontWeight: '600' },
  cardPlayButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#1e293b', alignItems: 'center', justifyContent: 'center' },


  videoPoster: { position: 'absolute', width: '100%', aspectRatio: 16 / 9, resizeMode: 'cover', opacity: 0.72 },
  video: { width: '100%', aspectRatio: 16 / 9, backgroundColor: '#000000' },
  videoEmpty: { alignItems: 'center', justifyContent: 'center', padding: 18, backgroundColor: '#020617' },
  videoEmptyTitle: { color: '#f8fafc', fontSize: 14, fontWeight: '900' },
  videoEmptyText: { color: '#94a3b8', fontSize: 12, marginTop: 4, textAlign: 'center' },
  videoProtocol: { color: '#02130f', fontSize: 10, fontWeight: '900', backgroundColor: '#34d399', borderRadius: 999, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 5 },

  disabled: { opacity: 0.36 },

  cameraStage: { gap: 16 },
  cameraDetailHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 4, paddingBottom: 2 },
  headerIconButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  cameraDetailTitle: { color: '#ffffff', fontSize: 18, fontWeight: '800', textAlign: 'center' },
  cameraDetailSubtitle: { color: '#34d399', fontSize: 10, fontWeight: '800', textAlign: 'center', textTransform: 'uppercase', letterSpacing: 1.1, marginTop: 3 },
  singleVideoCard: { borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', backgroundColor: '#000000', borderRadius: 32, overflow: 'hidden', shadowColor: '#000', shadowOpacity: 0.55, shadowRadius: 28, elevation: 10 },
  singleVideoTopOverlay: { position: 'absolute', left: 12, right: 12, top: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  liveNowText: { color: '#d1fae5', fontSize: 11, fontWeight: '900', letterSpacing: 1.3, backgroundColor: 'rgba(0,0,0,0.64)', borderRadius: 999, overflow: 'hidden', paddingHorizontal: 12, paddingVertical: 7, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  quickActionsGrid: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, marginVertical: 6 },
  quickActionButton: { flex: 1, alignItems: 'center', gap: 8 },
  quickActionIcon: { width: 56, height: 56, borderRadius: 18, backgroundColor: '#0f172a', borderWidth: 1, borderColor: '#1e293b', alignItems: 'center', justifyContent: 'center' },
  quickActionIconActive: { backgroundColor: '#10b981', borderColor: '#10b981', shadowColor: '#10b981', shadowOpacity: 0.32, shadowRadius: 15, elevation: 7 },
  quickActionLabel: { color: '#94a3b8', fontSize: 12, fontWeight: '700' },
  quickActionSoon: { color: '#64748b', fontSize: 9, fontWeight: '800', marginTop: -5 },
  ptzCardPremium: { backgroundColor: 'transparent', borderRadius: 0, padding: 0, gap: 18, borderWidth: 0 },
  ptzFeedback: { color: '#02130f', backgroundColor: '#34d399', overflow: 'hidden', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, fontSize: 10, fontWeight: '900' },
  ptzConsole: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 18, backgroundColor: '#0f172a', borderRadius: 32, borderWidth: 1, borderColor: 'rgba(30,41,59,0.9)', paddingVertical: 24, paddingHorizontal: 10, shadowColor: '#000', shadowOpacity: 0.45, shadowRadius: 22, elevation: 8 },
  ptzDpad: { width: 224, height: 224, borderRadius: 112, backgroundColor: '#0f172a', borderWidth: 1, borderColor: '#1e293b', position: 'relative', alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.52, shadowRadius: 24, elevation: 10 },
  ptzRoundButton: { position: 'absolute', width: 48, height: 48, borderRadius: 24, backgroundColor: 'transparent', borderWidth: 0, alignItems: 'center', justifyContent: 'center' },
  ptzRoundButtonActive: { backgroundColor: '#10b981', transform: [{ scale: 0.9 }] },
  ptzRoundText: { color: '#64748b', fontSize: 32, fontWeight: '900' },
  ptzRoundTextActive: { color: '#02130f' },
  ptzUp: { top: 12, left: 88 },
  ptzLeft: { left: 12, top: 88 },
  ptzRight: { right: 12, top: 88 },
  ptzDown: { bottom: 12, left: 88 },
  ptzNub: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#1e293b', borderWidth: 4, borderColor: '#334155', alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.42, shadowRadius: 16, elevation: 5 },
  ptzNubInner: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(51,65,85,0.52)' },
  mosaicHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 2, marginBottom: 4 },
  mosaicTitle: { color: '#ffffff', fontSize: 25, fontWeight: '900' },
  editLayoutButton: { borderWidth: 1, borderColor: 'rgba(52,211,153,0.24)', backgroundColor: 'rgba(16,185,129,0.10)', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, alignItems: 'center' },
  editLayoutText: { color: '#34d399', fontSize: 13, fontWeight: '800' },
  editLayoutSoon: { color: '#64748b', fontSize: 9, fontWeight: '800', marginTop: 1 },
  groupFilterRow: { gap: 9, paddingRight: 16, paddingBottom: 2 },
  groupFilterChip: { borderWidth: 1, borderColor: '#1e293b', backgroundColor: '#0f172a', borderRadius: 999, paddingHorizontal: 14, paddingVertical: 9 },
  groupFilterChipActive: { backgroundColor: '#10b981', borderColor: '#10b981' },
  groupFilterText: { color: '#94a3b8', fontSize: 12, fontWeight: '900' },
  groupFilterTextActive: { color: '#02130f' },
  mosaicGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  mosaicTile: { width: '48.55%', aspectRatio: 1, backgroundColor: '#0f172a', borderRadius: 18, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(30,41,59,0.86)', shadowColor: '#000', shadowOpacity: 0.34, shadowRadius: 14, elevation: 4 },
  mosaicImage: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover', opacity: 0.84 },
  mosaicFallback: { position: 'absolute', width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center', backgroundColor: '#111827' },
  mosaicFallbackText: { color: '#34d399', fontSize: 11, fontWeight: '900', letterSpacing: 2 },
  mosaicShade: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(2,6,23,0.18)' },
  mosaicStatus: { position: 'absolute', right: 10, top: 10, width: 10, height: 10, borderRadius: 5, borderWidth: 1, borderColor: 'rgba(2,6,23,0.8)' },
  mosaicStatusOnline: { backgroundColor: '#34d399' },
  mosaicStatusOffline: { backgroundColor: '#fb7185' },
  mosaicFooter: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 12, paddingTop: 28, paddingBottom: 10, backgroundColor: 'rgba(2,6,23,0.62)' },
  mosaicCameraName: { color: '#ffffff', fontSize: 12, fontWeight: '800' },

  recordingsTitle: { color: '#ffffff', fontSize: 30, fontWeight: '900', marginBottom: 4 },
  recordingsSubtitle: { color: '#94a3b8', fontSize: 14, lineHeight: 20, marginBottom: 6 },
  recordingCameraList: { gap: 12 },
  recordingCameraCard: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#0f172a', borderRadius: 28, borderWidth: 1, borderColor: 'rgba(30,41,59,0.86)', padding: 12, shadowColor: '#000', shadowOpacity: 0.3, shadowRadius: 16, elevation: 4 },
  recordingCameraCardActive: { borderColor: 'rgba(52,211,153,0.55)' },
  recordingCameraThumb: { width: 96, height: 80, borderRadius: 18, backgroundColor: '#1e293b', overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  recordingCameraImage: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover', opacity: 0.9 },
  recordDot: { position: 'absolute', left: 7, top: 7, width: 9, height: 9, borderRadius: 5, backgroundColor: '#f43f5e', shadowColor: '#f43f5e', shadowOpacity: 0.6, shadowRadius: 8, elevation: 4 },
  recordingCameraBody: { flex: 1 },
  recordingCameraTitle: { color: '#ffffff', fontSize: 16, fontWeight: '800' },
  recordingCameraMeta: { color: '#94a3b8', fontSize: 12, marginTop: 2 },
  recordingCameraHistory: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 9 },
  recordingCameraHistoryText: { color: '#cbd5e1', fontSize: 10, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 },
  recordingCameraArrow: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#1e293b', alignItems: 'center', justifyContent: 'center' },
  recordingCameraArrowText: { color: '#94a3b8', fontSize: 28, lineHeight: 30, fontWeight: '300' },
  playbackPlayerCard: { borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', backgroundColor: '#0f172a', borderRadius: 32, padding: 13, gap: 13, shadowColor: '#000', shadowOpacity: 0.42, shadowRadius: 22, elevation: 7 },
  playbackHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  playbackTitle: { color: '#f8fafc', fontSize: 16, fontWeight: '900' },
  playbackVideo: { width: '100%', aspectRatio: 16 / 9, backgroundColor: '#000000', borderRadius: 22, overflow: 'hidden' },
  closePlaybackButton: { borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', backgroundColor: '#111827', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  closePlaybackText: { color: '#e2e8f0', fontSize: 11, fontWeight: '900' },
  dateCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, backgroundColor: '#0f172a', borderWidth: 1, borderColor: '#1e293b', borderRadius: 18, padding: 10 },
  dateCardCenter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  dateCardText: { color: '#ffffff', fontSize: 14, fontWeight: '800' },
  dateNavButton: { width: 42, height: 38, borderRadius: 14, backgroundColor: '#1e293b', alignItems: 'center', justifyContent: 'center' },
  dateNavButtonText: { color: '#cbd5e1', fontSize: 28, lineHeight: 30, fontWeight: '300' },
  recordingTimeline: { marginLeft: 12, paddingLeft: 22, borderLeftWidth: 2, borderColor: '#1e293b', gap: 28 },
  recordingTimelineItem: { position: 'relative' },
  recordingTimelineDot: { position: 'absolute', left: -30, top: 4, width: 14, height: 14, borderRadius: 7, backgroundColor: '#020617', borderWidth: 2, borderColor: '#10b981' },
  recordingTimelineContent: { gap: 12 },
  recordingTimelineTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
  recordingTimelineTime: { color: '#34d399', fontSize: 14, fontWeight: '900' },
  recordingTimelineEvent: { color: '#cbd5e1', fontSize: 13, marginTop: 4 },
  downloadCircle: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#1e293b', alignItems: 'center', justifyContent: 'center' },
  recordingPreview: { height: 132, borderRadius: 14, overflow: 'hidden', borderWidth: 1, borderColor: '#334155', backgroundColor: '#1e293b', alignItems: 'center', justifyContent: 'center' },
  recordingPreviewImage: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover', opacity: 0.62 },
  recordingPreviewShade: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(2,6,23,0.18)' },
  recordingPlayCircle: { width: 52, height: 52, borderRadius: 26, backgroundColor: 'rgba(15,23,42,0.82)', alignItems: 'center', justifyContent: 'center' },
  recordingDurationBadge: { position: 'absolute', right: 9, bottom: 9, color: '#ffffff', backgroundColor: 'rgba(0,0,0,0.62)', borderRadius: 6, overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4, fontSize: 10, fontWeight: '800' },
  rowButtons: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  smallButton: { borderRadius: 999, backgroundColor: '#10b981', paddingHorizontal: 15, paddingVertical: 10 },
  smallButtonText: { color: '#02130f', fontWeight: '900', fontSize: 12 },
  smallButtonDark: { borderRadius: 999, backgroundColor: '#111827', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', paddingHorizontal: 15, paddingVertical: 10 },
  smallButtonDarkText: { color: '#e2e8f0', fontWeight: '900', fontSize: 12 },
  emptyCard: { borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', backgroundColor: '#0f172a', borderRadius: 28, padding: 24, alignItems: 'center' },
  emptyTitle: { color: '#f8fafc', fontSize: 16, fontWeight: '900' },
  emptyText: { color: '#94a3b8', textAlign: 'center', marginTop: 6, lineHeight: 18 },

  profileScreenTitle: { color: '#ffffff', fontSize: 25, fontWeight: '900', marginBottom: 6 },
  profileSimpleCard: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#0f172a', borderRadius: 28, borderWidth: 1, borderColor: '#1e293b', padding: 18, marginBottom: 8 },
  profileSimpleAvatar: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#1e293b', alignItems: 'center', justifyContent: 'center' },
  profileSimpleName: { color: '#ffffff', fontSize: 16, fontWeight: '800' },
  profileSimplePlan: { color: '#34d399', fontSize: 12, fontWeight: '700', marginTop: 3 },
  settingsList: { gap: 12 },
  settingsRow: { backgroundColor: '#0f172a', borderRadius: 18, borderWidth: 1, borderColor: '#1e293b', padding: 16 },
  settingsRowDisabled: { opacity: 0.54 },
  settingsRowText: { color: '#cbd5e1', fontSize: 14, fontWeight: '700' },
  settingsSoonText: { color: '#64748b', fontSize: 11, fontWeight: '800', marginTop: 5 },
  logoutButton: { width: '100%', height: 54, borderRadius: 20, backgroundColor: 'rgba(244,63,94,0.14)', borderWidth: 1, borderColor: 'rgba(244,63,94,0.30)', alignItems: 'center', justifyContent: 'center', marginTop: 8 },
  logoutText: { color: '#fda4af', fontSize: 14, fontWeight: '900' },
});
