import { StyleSheet } from 'react-native';
import { BOTTOM_SAFE, TOP_SAFE } from '../config';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#f3f4f6' },
  content: { padding: 16, paddingTop: TOP_SAFE + 18, paddingBottom: BOTTOM_SAFE + 118, backgroundColor: '#f3f4f6' },
  page: { gap: 18 },
  dashboardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  dashboardTitle: { color: '#111827', fontSize: 28, fontWeight: '900', letterSpacing: -0.6 },
  dashboardSubtitle: { color: '#6b7280', fontSize: 14, marginTop: 4, fontWeight: '600' },
  previewLimitHint: { color: '#9ca3af', fontSize: 11, lineHeight: 16, marginTop: 6, fontWeight: '700' },


  groupBlock: { gap: 13, marginTop: 4 },
  groupHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 3 },
  groupTitle: { color: '#111827', fontSize: 14, fontWeight: '900' },
  groupCount: { color: '#6b7280', fontSize: 12, fontWeight: '800' },
  cameraCard: { height: 204, borderRadius: 28, overflow: 'hidden', backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', shadowColor: '#111827', shadowOpacity: 0.12, shadowRadius: 18, elevation: 5 },
  cameraPreview: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: '#e5e7eb', overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  cameraPreviewImage: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover', opacity: 0.9 },
  cameraPreviewFallback: { position: 'absolute', width: '100%', height: '100%', backgroundColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center' },
  cameraPreviewShade: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(2,6,23,0.08)' },
  cameraPreviewText: { color: '#2563eb', fontSize: 12, fontWeight: '900', letterSpacing: 2.2 },
  liveBadge: { position: 'absolute', left: 18, top: 18, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 7, flexDirection: 'row', gap: 7, alignItems: 'center', borderWidth: 1 },
  liveBadgeOnline: { backgroundColor: 'rgba(17,24,39,0.55)', borderColor: 'rgba(255,255,255,0.22)' },
  liveBadgeOffline: { backgroundColor: 'rgba(244,63,94,0.18)', borderColor: 'rgba(244,63,94,0.36)' },
  liveDot: { width: 7, height: 7, borderRadius: 4 },
  liveDotOnline: { backgroundColor: '#22c55e' },
  liveDotOffline: { backgroundColor: '#fb7185' },
  liveBadgeText: { fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  liveBadgeTextOnline: { color: '#dcfce7' },
  liveBadgeTextOffline: { color: '#fecdd3' },
  cameraCardBody: { position: 'absolute', left: 0, right: 0, bottom: 0, minHeight: 58, zIndex: 5, gap: 2, backgroundColor: '#0f172a', borderTopWidth: 1, borderColor: 'rgba(30,41,59,0.72)', paddingHorizontal: 18, paddingVertical: 9 },
  cameraOverlayBody: { position: 'absolute', left: 0, right: 0, bottom: 0, zIndex: 5, paddingHorizontal: 18, paddingTop: 54, paddingBottom: 16, backgroundColor: 'rgba(2,6,23,0.01)' },
  cameraOverlayTextBlock: { flex: 1, paddingRight: 10 },
  cameraCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  cameraName: { color: '#ffffff', fontWeight: '900', fontSize: 17, flexShrink: 1, letterSpacing: 0.1, textShadowColor: 'rgba(0,0,0,0.65)', textShadowRadius: 8 },
  cameraMeta: { color: '#d1d5db', fontSize: 12, marginTop: 2, fontWeight: '700', textShadowColor: 'rgba(0,0,0,0.65)', textShadowRadius: 8 },
  cardPlayButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#2563eb', alignItems: 'center', justifyContent: 'center', shadowColor: '#2563eb', shadowOpacity: 0.34, shadowRadius: 14, elevation: 8 },


  videoPoster: { position: 'absolute', width: '100%', aspectRatio: 16 / 9, resizeMode: 'cover', opacity: 0.72 },
  video: { width: '100%', aspectRatio: 16 / 9, backgroundColor: '#000000' },
  videoEmpty: { alignItems: 'center', justifyContent: 'center', padding: 18, backgroundColor: '#111827' },
  videoEmptyTitle: { color: '#f8fafc', fontSize: 14, fontWeight: '900' },
  videoEmptyText: { color: '#d1d5db', fontSize: 12, marginTop: 4, textAlign: 'center' },
  videoProtocol: { color: '#ffffff', fontSize: 10, fontWeight: '900', backgroundColor: '#2563eb', borderRadius: 999, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 5 },

  disabled: { opacity: 0.36 },

  cameraStage: { gap: 16 },
  cameraDetailHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 4, paddingBottom: 2 },
  headerIconButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  cameraDetailTitle: { color: '#111827', fontSize: 18, fontWeight: '800', textAlign: 'center' },
  cameraDetailSubtitle: { color: '#2563eb', fontSize: 10, fontWeight: '800', textAlign: 'center', textTransform: 'uppercase', letterSpacing: 1.1, marginTop: 3 },
  singleVideoCard: { borderWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#000000', borderRadius: 28, overflow: 'hidden', shadowColor: '#111827', shadowOpacity: 0.18, shadowRadius: 22, elevation: 8 },
  singleVideoTopOverlay: { position: 'absolute', left: 12, right: 12, top: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  liveNowText: { color: '#d1fae5', fontSize: 11, fontWeight: '900', letterSpacing: 1.3, backgroundColor: 'rgba(0,0,0,0.64)', borderRadius: 999, overflow: 'hidden', paddingHorizontal: 12, paddingVertical: 7, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  quickActionsGrid: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, marginVertical: 6 },
  quickActionButton: { flex: 1, alignItems: 'center', gap: 8 },
  quickActionIcon: { width: 56, height: 56, borderRadius: 18, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center', shadowColor: '#111827', shadowOpacity: 0.08, shadowRadius: 10, elevation: 3 },
  quickActionIconActive: { backgroundColor: '#2563eb', borderColor: '#2563eb', shadowColor: '#2563eb', shadowOpacity: 0.28, shadowRadius: 15, elevation: 7 },
  quickActionLabel: { color: '#4b5563', fontSize: 12, fontWeight: '700' },
  quickActionSoon: { color: '#9ca3af', fontSize: 9, fontWeight: '800', marginTop: -5 },
  liveVideoSideActions: { position: 'absolute', right: 14, top: '34%', gap: 14, zIndex: 12 },
  liveVideoRoundAction: { width: 42, height: 42, borderRadius: 21, backgroundColor: 'rgba(17,24,39,0.52)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.20)' },
  liveVideoRoundActionActive: { backgroundColor: '#2563eb', borderColor: '#2563eb' },
  liveVideoBottomControls: { position: 'absolute', left: 16, bottom: 14, flexDirection: 'row', alignItems: 'center', gap: 18, zIndex: 12 },
  liveSpeedText: { color: '#ffffff', fontSize: 13, fontWeight: '900' },
  ptzVideoOverlay: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, zIndex: 20, backgroundColor: 'rgba(0,0,0,0.46)', alignItems: 'center', justifyContent: 'center' },
  ptzOverlayClose: { position: 'absolute', right: 14, top: 14, width: 30, height: 30, borderRadius: 15, backgroundColor: 'rgba(0,0,0,0.48)', alignItems: 'center', justifyContent: 'center' },
  ptzOverlayCloseText: { color: '#ffffff', fontSize: 12, fontWeight: '900' },
  ptzOverlayTitle: { color: '#ffffff', fontSize: 14, fontWeight: '800', marginBottom: 16, textShadowColor: 'rgba(0,0,0,0.5)', textShadowRadius: 6 },
  ptzOverlayFeedback: { color: '#ffffff', fontSize: 10, fontWeight: '900', marginBottom: 8, backgroundColor: 'rgba(37,99,235,0.78)', borderRadius: 999, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 5 },
  ptzOverlayDpad: { width: 164, height: 164, borderRadius: 82, backgroundColor: 'rgba(255,255,255,0.12)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.25)', alignItems: 'center', justifyContent: 'center' },
  ptzOverlayButton: { position: 'absolute', width: 44, height: 44, borderRadius: 22, backgroundColor: 'transparent', borderWidth: 0, alignItems: 'center', justifyContent: 'center' },
  ptzOverlayButtonActive: { backgroundColor: 'rgba(255,255,255,0.30)', transform: [{ scale: 0.94 }] },
  ptzOverlayButtonText: { color: '#ffffff', fontSize: 30, fontWeight: '800' },
  ptzOverlayButtonTextActive: { color: '#ffffff' },
  ptzOverlayUp: { top: 7, left: 60 },
  ptzOverlayDown: { bottom: 7, left: 60 },
  ptzOverlayLeft: { left: 7, top: 60 },
  ptzOverlayRight: { right: 7, top: 60 },
  ptzOverlayNub: { width: 58, height: 58, borderRadius: 29, backgroundColor: 'rgba(255,255,255,0.20)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.34)', alignItems: 'center', justifyContent: 'center' },
  ptzOverlayNubInner: { width: 18, height: 18, borderRadius: 9, backgroundColor: 'rgba(255,255,255,0.62)' },
  ptzCardPremium: { backgroundColor: 'transparent', borderRadius: 0, padding: 0, gap: 18, borderWidth: 0 },
  ptzFeedback: { color: '#02130f', backgroundColor: '#34d399', overflow: 'hidden', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, fontSize: 10, fontWeight: '900' },
  ptzConsole: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 18, backgroundColor: '#0f172a', borderRadius: 32, borderWidth: 1, borderColor: 'rgba(30,41,59,0.9)', paddingVertical: 24, paddingHorizontal: 10, shadowColor: '#000', shadowOpacity: 0.45, shadowRadius: 22, elevation: 8 },
  ptzDpad: { width: 224, height: 224, borderRadius: 112, backgroundColor: '#0f172a', borderWidth: 1, borderColor: '#1e293b', position: 'relative', alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.52, shadowRadius: 24, elevation: 10 },
  ptzRoundButton: { position: 'absolute', width: 48, height: 48, borderRadius: 24, backgroundColor: 'transparent', borderWidth: 0, alignItems: 'center', justifyContent: 'center' },
  ptzRoundButtonActive: { backgroundColor: '#10b981', transform: [{ scale: 0.9 }] },
  ptzRoundText: { color: '#64748b', fontSize: 32, fontWeight: '900' },
  ptzRoundTextActive: { color: '#02130f' },
  ptzUp: { top: 12, left: 88 },
  ptzLeft: { left: 12, top: 88 },
  ptzRight: { right: 12, top: 88 },
  ptzDown: { bottom: 12, left: 88 },
  ptzNub: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#1e293b', borderWidth: 4, borderColor: '#334155', alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.42, shadowRadius: 16, elevation: 5 },
  ptzNubInner: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(51,65,85,0.52)' },
  mosaicHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 2, marginBottom: 4 },
  mosaicTitle: { color: '#111827', fontSize: 25, fontWeight: '900' },
  mosaicSubtitle: { color: '#6b7280', fontSize: 13, fontWeight: '700', marginTop: 3, lineHeight: 18 },
  editLayoutButton: { borderWidth: 1, borderColor: 'rgba(52,211,153,0.24)', backgroundColor: 'rgba(16,185,129,0.10)', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, alignItems: 'center' },
  editLayoutText: { color: '#34d399', fontSize: 13, fontWeight: '800' },
  editLayoutSoon: { color: '#64748b', fontSize: 9, fontWeight: '800', marginTop: 1 },
  areaCreatorCard: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 22, padding: 10, shadowColor: '#111827', shadowOpacity: 0.08, shadowRadius: 14, elevation: 3 },
  areaCreatorInput: { flex: 1, minHeight: 44, color: '#111827', fontSize: 13, fontWeight: '700', paddingHorizontal: 10 },
  areaCreatorButton: { height: 44, borderRadius: 16, paddingHorizontal: 14, backgroundColor: '#2563eb', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  areaCreatorButtonText: { color: '#ffffff', fontSize: 12, fontWeight: '900' },
  groupFilterRow: { gap: 9, paddingRight: 16, paddingBottom: 2 },
  groupFilterChip: { borderWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#ffffff', borderRadius: 999, paddingHorizontal: 14, paddingVertical: 9 },
  groupFilterChipActive: { backgroundColor: '#2563eb', borderColor: '#2563eb' },
  groupFilterChipActiveSoft: { backgroundColor: 'rgba(37,99,235,0.10)', borderColor: 'rgba(37,99,235,0.28)' },
  groupFilterText: { color: '#6b7280', fontSize: 12, fontWeight: '900' },
  groupFilterTextActive: { color: '#ffffff' },
  groupFilterTextActiveSoft: { color: '#2563eb' },
  areaEditorCard: { backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#dbeafe', borderRadius: 24, padding: 14, gap: 14, shadowColor: '#111827', shadowOpacity: 0.08, shadowRadius: 14, elevation: 3 },
  areaEditorHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  areaEditorTitle: { color: '#111827', fontSize: 16, fontWeight: '900' },
  areaEditorSubtitle: { color: '#6b7280', fontSize: 12, fontWeight: '700', marginTop: 2 },
  areaDeleteButton: { borderWidth: 1, borderColor: 'rgba(244,63,94,0.26)', backgroundColor: 'rgba(244,63,94,0.10)', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  areaDeleteText: { color: '#fda4af', fontSize: 11, fontWeight: '900' },
  cameraPickerRow: { gap: 8, paddingRight: 12 },
  cameraPickerChip: { borderWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#f9fafb', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  cameraPickerChipActive: { backgroundColor: 'rgba(37,99,235,0.12)', borderColor: 'rgba(37,99,235,0.34)' },
  cameraPickerText: { color: '#6b7280', fontSize: 11, fontWeight: '900' },
  cameraPickerTextActive: { color: '#2563eb' },
  cameraSelectionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  cameraSelectionCard: { width: '48.4%', borderRadius: 18, backgroundColor: '#f9fafb', borderWidth: 1, borderColor: '#e5e7eb', padding: 8, gap: 8 },
  cameraSelectionCardActive: { borderColor: '#2563eb', backgroundColor: '#eff6ff' },
  cameraSelectionThumb: { height: 76, borderRadius: 14, backgroundColor: '#e5e7eb', overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  cameraSelectionImage: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover' },
  cameraSelectionCheck: { position: 'absolute', right: 7, top: 7, minWidth: 26, height: 26, borderRadius: 13, backgroundColor: 'rgba(255,255,255,0.86)', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  cameraSelectionCheckActive: { backgroundColor: '#2563eb' },
  cameraSelectionCheckText: { color: '#374151', fontSize: 11, fontWeight: '900' },
  cameraSelectionCheckTextActive: { color: '#ffffff' },
  cameraSelectionName: { color: '#111827', fontSize: 12, fontWeight: '800' },
  mosaicSectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 2 },
  mosaicSectionTitle: { color: '#111827', fontSize: 15, fontWeight: '900' },
  mosaicSectionCount: { color: '#6b7280', fontSize: 12, fontWeight: '800' },
  mosaicGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  mosaicTile: { width: '48.55%', aspectRatio: 1, backgroundColor: '#ffffff', borderRadius: 18, overflow: 'hidden', borderWidth: 1, borderColor: '#e5e7eb', shadowColor: '#111827', shadowOpacity: 0.12, shadowRadius: 14, elevation: 4 },
  mosaicImage: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover', opacity: 0.84 },
  mosaicFallback: { position: 'absolute', width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center', backgroundColor: '#e5e7eb' },
  mosaicFallbackText: { color: '#2563eb', fontSize: 11, fontWeight: '900', letterSpacing: 2 },
  mosaicShade: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(2,6,23,0.18)' },
  mosaicStatus: { position: 'absolute', right: 10, top: 10, width: 10, height: 10, borderRadius: 5, borderWidth: 1, borderColor: 'rgba(2,6,23,0.8)' },
  mosaicStatusOnline: { backgroundColor: '#34d399' },
  mosaicStatusOffline: { backgroundColor: '#fb7185' },
  mosaicFooter: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 12, paddingTop: 28, paddingBottom: 10, backgroundColor: 'rgba(2,6,23,0.62)' },
  mosaicCameraName: { color: '#ffffff', fontSize: 12, fontWeight: '800' },

  recordingsTitle: { color: '#111827', fontSize: 30, fontWeight: '900', marginBottom: 4 },
  recordingsSubtitle: { color: '#6b7280', fontSize: 14, lineHeight: 20, marginBottom: 6 },
  recordingCameraList: { gap: 12 },
  recordingCameraCard: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#ffffff', borderRadius: 28, borderWidth: 1, borderColor: '#e5e7eb', padding: 12, shadowColor: '#111827', shadowOpacity: 0.08, shadowRadius: 16, elevation: 4 },
  recordingCameraCardActive: { borderColor: 'rgba(37,99,235,0.55)' },
  recordingCameraThumb: { width: 96, height: 80, borderRadius: 18, backgroundColor: '#e5e7eb', overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  recordingCameraImage: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover', opacity: 0.9 },
  recordDot: { position: 'absolute', left: 7, top: 7, width: 9, height: 9, borderRadius: 5, backgroundColor: '#f43f5e', shadowColor: '#f43f5e', shadowOpacity: 0.6, shadowRadius: 8, elevation: 4 },
  recordingCameraBody: { flex: 1 },
  recordingCameraTitle: { color: '#111827', fontSize: 16, fontWeight: '800' },
  recordingCameraMeta: { color: '#6b7280', fontSize: 12, marginTop: 2 },
  recordingCameraHistory: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 9 },
  recordingCameraHistoryText: { color: '#2563eb', fontSize: 10, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 },
  recordingCameraArrow: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#f3f4f6', alignItems: 'center', justifyContent: 'center' },
  recordingCameraArrowText: { color: '#6b7280', fontSize: 28, lineHeight: 30, fontWeight: '300' },
  playbackPlayerCard: { borderWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#ffffff', borderRadius: 32, padding: 13, gap: 13, shadowColor: '#111827', shadowOpacity: 0.12, shadowRadius: 22, elevation: 7 },
  playbackHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  playbackTitle: { color: '#111827', fontSize: 18, fontWeight: '900', letterSpacing: -0.2 },
  cloudReplayStage: { position: 'relative', borderRadius: 24, overflow: 'hidden', backgroundColor: '#000000', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  playbackVideo: { width: '100%', aspectRatio: 16 / 9, backgroundColor: '#000000' },
  cloudReplayTopBar: { position: 'absolute', left: 12, right: 12, top: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cloudReplayBadge: { color: '#ffffff', fontSize: 10, fontWeight: '900', letterSpacing: 1.1, backgroundColor: '#2563eb', borderWidth: 1, borderColor: 'rgba(255,255,255,0.28)', borderRadius: 999, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 6 },
  cloudReplayTime: { color: '#ffffff', fontSize: 10, fontWeight: '900', backgroundColor: 'rgba(0,0,0,0.58)', borderRadius: 999, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 6 },
  closePlaybackButton: { borderWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#f9fafb', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  closePlaybackText: { color: '#111827', fontSize: 11, fontWeight: '900' },
  dateCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 18, padding: 10 },
  dateCardCenter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  dateCardText: { color: '#111827', fontSize: 14, fontWeight: '800' },
  dateNavButton: { width: 42, height: 38, borderRadius: 14, backgroundColor: '#f3f4f6', alignItems: 'center', justifyContent: 'center' },
  dateNavButtonText: { color: '#6b7280', fontSize: 28, lineHeight: 30, fontWeight: '300' },
  replayDaysRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 5, backgroundColor: '#ffffff', borderRadius: 22, padding: 10, borderWidth: 1, borderColor: '#e5e7eb' },
  replayDayPill: { width: 42, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', opacity: 0.46 },
  replayDayPillActive: { opacity: 1, borderWidth: 2, borderColor: '#e5e7eb', backgroundColor: '#ffffff' },
  replayDayName: { color: '#6b7280', fontSize: 10, fontWeight: '700', textTransform: 'capitalize' },
  replayDayNameActive: { color: '#111827' },
  replayDayNumber: { color: '#6b7280', fontSize: 14, fontWeight: '800', marginTop: 1 },
  replayDayNumberActive: { color: '#111827' },
  replayTimelineRuler: { height: 104, borderRadius: 20, backgroundColor: '#f9fafb', borderWidth: 1, borderColor: '#e5e7eb', overflow: 'hidden', justifyContent: 'center' },
  replayTimelineLabels: { position: 'absolute', left: 14, right: 14, top: 12, flexDirection: 'row', justifyContent: 'space-between' },
  replayTimelineLabel: { color: '#9ca3af', fontSize: 10, fontWeight: '800' },
  replayTicks: { position: 'absolute', left: 14, right: 14, top: 36, flexDirection: 'row', justifyContent: 'space-between', opacity: 0.35 },
  replayTick: { width: 1, height: 7, backgroundColor: '#4b5563' },
  replayTickMajor: { height: 14 },
  replayTrack: { position: 'absolute', left: 16, right: 16, top: 57, height: 12, borderRadius: 999, overflow: 'hidden', backgroundColor: '#e5e7eb', flexDirection: 'row' },
  replayTrackSegmentBlue: { backgroundColor: '#60a5fa' },
  replayTrackSegmentOrange: { backgroundColor: '#fb923c' },
  replayTrackGap: { width: 8, backgroundColor: 'transparent' },
  replayPlayhead: { position: 'absolute', left: '50%', top: 0, bottom: 0, width: 2, backgroundColor: '#ef4444', alignItems: 'center', shadowColor: '#ef4444', shadowOpacity: 0.6, shadowRadius: 8, elevation: 4 },
  replayPlayheadCap: { width: 12, height: 12, backgroundColor: '#ef4444', borderBottomLeftRadius: 3, borderBottomRightRadius: 3 },
  replayFilterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  replayFilterActive: { backgroundColor: '#2563eb', borderRadius: 999, paddingHorizontal: 16, paddingVertical: 8 },
  replayFilterActiveText: { color: '#ffffff', fontSize: 12, fontWeight: '800' },
  replayFilter: { backgroundColor: '#ffffff', borderRadius: 999, paddingHorizontal: 16, paddingVertical: 8, borderWidth: 1, borderColor: '#dbeafe' },
  replayFilterText: { color: '#2563eb', fontSize: 12, fontWeight: '800' },
  replayGridHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  replayGridDate: { color: '#6b7280', fontSize: 14, fontWeight: '800' },
  replayGridCount: { color: '#9ca3af', fontSize: 12, fontWeight: '800' },
  replayEventGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  replayEventCard: { width: '31.8%', gap: 6 },
  replayEventThumb: { aspectRatio: 4 / 3, borderRadius: 12, backgroundColor: '#e5e7eb', overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  replayEventIcon: { position: 'absolute', left: 6, bottom: 6, width: 22, height: 22, borderRadius: 11, backgroundColor: 'rgba(17,24,39,0.82)', alignItems: 'center', justifyContent: 'center' },
  replayEventPlay: { width: 34, height: 34, borderRadius: 17, backgroundColor: 'rgba(37,99,235,0.88)', alignItems: 'center', justifyContent: 'center' },
  replayEventFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  replayEventTime: { color: '#6b7280', textAlign: 'center', fontSize: 12, fontWeight: '800' },
  replayEventDownload: { width: 22, height: 22, borderRadius: 11, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center' },
  replayEventMeta: { color: '#9ca3af', fontSize: 10, fontWeight: '700' },
  recordingTimelineCompact: { marginLeft: 12, paddingLeft: 22, borderLeftWidth: 2, borderColor: '#e5e7eb', gap: 16 },
  recordingTimeline: { marginLeft: 12, paddingLeft: 22, borderLeftWidth: 2, borderColor: '#e5e7eb', gap: 28 },
  recordingTimelineItem: { position: 'relative' },
  recordingTimelineDot: { position: 'absolute', left: -30, top: 4, width: 14, height: 14, borderRadius: 7, backgroundColor: '#ffffff', borderWidth: 2, borderColor: '#2563eb' },
  recordingTimelineContent: { gap: 12 },
  recordingTimelineTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
  recordingTimelineTime: { color: '#2563eb', fontSize: 14, fontWeight: '900' },
  recordingTimelineEvent: { color: '#6b7280', fontSize: 13, marginTop: 4 },
  downloadCircle: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#f3f4f6', alignItems: 'center', justifyContent: 'center' },
  recordingPreview: { height: 150, borderRadius: 18, overflow: 'hidden', borderWidth: 1, borderColor: '#334155', backgroundColor: '#1e293b', alignItems: 'center', justifyContent: 'center' },
  recordingPreviewImage: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover', opacity: 0.68 },
  recordingPreviewShade: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(2,6,23,0.24)' },
  recordingCloudBadge: { position: 'absolute', left: 10, top: 10, backgroundColor: 'rgba(2,6,23,0.72)', borderWidth: 1, borderColor: 'rgba(52,211,153,0.28)', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  recordingCloudBadgeText: { color: '#d1fae5', fontSize: 10, fontWeight: '900', letterSpacing: 0.7 },
  recordingPlayOuter: { alignItems: 'center', justifyContent: 'center', gap: 8 },
  recordingPlayCircle: { width: 62, height: 62, borderRadius: 31, backgroundColor: '#34d399', alignItems: 'center', justifyContent: 'center', shadowColor: '#34d399', shadowOpacity: 0.38, shadowRadius: 18, elevation: 9 },
  recordingPlayLabel: { color: '#ffffff', fontSize: 11, fontWeight: '900', letterSpacing: 0.8, textShadowColor: 'rgba(0,0,0,0.7)', textShadowRadius: 8 },
  recordingDurationBadge: { position: 'absolute', right: 9, bottom: 9, color: '#ffffff', backgroundColor: 'rgba(0,0,0,0.62)', borderRadius: 6, overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4, fontSize: 10, fontWeight: '800' },
  rowButtons: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  smallButton: { borderRadius: 999, backgroundColor: '#2563eb', paddingHorizontal: 15, paddingVertical: 10 },
  smallButtonText: { color: '#ffffff', fontWeight: '900', fontSize: 12 },
  smallButtonDark: { borderRadius: 999, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', paddingHorizontal: 15, paddingVertical: 10 },
  smallButtonDarkText: { color: '#111827', fontWeight: '900', fontSize: 12 },
  emptyCard: { borderWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#ffffff', borderRadius: 28, padding: 24, alignItems: 'center' },
  emptyTitle: { color: '#111827', fontSize: 16, fontWeight: '900' },
  emptyText: { color: '#6b7280', textAlign: 'center', marginTop: 6, lineHeight: 18 },

  profileScreenTitle: { color: '#111827', fontSize: 25, fontWeight: '900', marginBottom: 6 },
  profileSimpleCard: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#ffffff', borderRadius: 28, borderWidth: 1, borderColor: '#e5e7eb', padding: 18, marginBottom: 8, shadowColor: '#111827', shadowOpacity: 0.08, shadowRadius: 14, elevation: 3 },
  profileSimpleAvatar: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#f3f4f6', alignItems: 'center', justifyContent: 'center' },
  profileSimpleName: { color: '#111827', fontSize: 16, fontWeight: '800' },
  profileSimplePlan: { color: '#2563eb', fontSize: 12, fontWeight: '700', marginTop: 3 },
  settingsList: { gap: 12 },
  settingsRow: { backgroundColor: '#ffffff', borderRadius: 18, borderWidth: 1, borderColor: '#e5e7eb', padding: 16 },
  settingsRowDisabled: { opacity: 0.54 },
  settingsRowText: { color: '#374151', fontSize: 14, fontWeight: '700' },
  settingsSoonText: { color: '#9ca3af', fontSize: 11, fontWeight: '800', marginTop: 5 },
  logoutButton: { width: '100%', height: 54, borderRadius: 20, backgroundColor: 'rgba(244,63,94,0.14)', borderWidth: 1, borderColor: 'rgba(244,63,94,0.30)', alignItems: 'center', justifyContent: 'center', marginTop: 8 },
  logoutText: { color: '#fda4af', fontSize: 14, fontWeight: '900' },
});
